mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - system
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "+.9563067.xyz"
  use-hosts: true
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  nameserver-policy:
    geosite:cn:
      - system
      - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://223.5.5.5/dns-query
  use-system-hosts: false
profile:
  store-selected: true
