mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - system
  nameserver:
    - 'tls://dns.google#手动选择兜底国家'
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  use-system-hosts: false
profile:
  store-selected: true
