mode: rule
log-level: info
unified-delay: true
dns:
  use-system-hosts: false
  enable: true
  fake-ip-filter:
    - "+.9563067.xyz"
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  nameserver-policy:
    geosite:cn:
      - system
      - https://223.5.5.5/dns-query
      - https://1.12.12.12/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.cfiec.net/dns-query
    - https://223.5.5.5/dns-query
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
profile:
  store-selected: true
